http://localhost:3000
GET /node/

http://localhost:3000
DELETE /node/:id

http://localhost:3000
POST /node/add
{"dg":{"upTime":0,"fuelConsumption":0,"power":0},"freezer":{"temperature":0,"power":0},"uid":"100001","name":"LAB1","supply":{"mains":{"r":0,"y":0,"b":0},"stabilizer":{"r":0,"y":0,"b":0},"amf":{"r":0,"y":0,"b":0}}}

http://localhost:3000 
POST /user/register
{
	  "user": {
			  "name": "Kaustubh",
				"email": "kaustubh.murumkar@gmail.com"
		}
}

http://localhost:3000
POST /node/modify?uid=100001
{
	"uid": "100001",
	"name": "LAB100"
}
